### ISSUE TITLE
Cannot add a new crop

### ISSUE THREAD

**Issue by pembo13** [pembertonc/NAITSe#13]
Clicking on "+ New" button under "Crops" brings up a dialog box for "New Country"

**Comment by pembertonc** [comment]
I am getting corruption of the browser memory previously loaded dialog boxes seem to remain in the memory.  all the different pages are loaded into different name sapaces but it seems the browser is cashing them and and ignoring the name space.

**Comment by pembertonc** [comment]
The issue should now be resolved
